---
language: generic
addons:
  snaps:
    - name: helm
      classic: true
script:
  - helm lint chart/pagerduty-oncall
  - bin/docker-build
deploy:
  provider: script
  script: bin/docker-push
  on:
    repo: travis-ci/pagerduty-oncall
    all_branches: true
notifications:
  email: false
