apiVersion: travisci.com/v1
kind: TrvsSecret
metadata:
  name: {{ include "pagerduty-oncall.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "pagerduty-oncall.name" . }}
    helm.sh/chart: {{ include "pagerduty-oncall.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  app: pagerduty-oncall
  env: pagerduty-oncall
