# Default values for pagerduty-oncall.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: travisci/pagerbot-oncall
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""
